#!/bin/bash
#myFile crontab_check.sh

OMD5SUM=`cat /root/crontabsum`
NMD5SUM=`md5sum /etc/crontab | cut -d " " -f 1`

if [ "$OMD5SUM" != "$NMD5SUM" ]
then
	md5sum /etc/crontab | cut -d " " -f 1 > /root/crontabsum
	mail -s "The file crontab was modified" root@localhost.com < /etc/crontab
fi


# 0 0    0 * 0-6   root    sh /root/crontab_check.sh
